# Generated by Django 5.2 on 2025-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_credits_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credits',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Client-generated UUID for offline sync idempotency', null=True, unique=True),
        ),
    ]
